---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/careers
  label: Careers
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - job-posting
- type: directory
  path: src/data
  label: Team Members
  create: documents
  match: "**/*.json"
  new_doc_ext: json
  templates:
  - team-member
upload_dir: assets/craft
public_path: "/assets/craft"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run develop
